/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSkeleton: typeof import('./components/AppSkeleton.vue')['default']
    BtcCard: typeof import('./../../../packages/shared-components/src/components/btc-card/index.vue')['default']
    BtcCascader: typeof import('./../../../packages/shared-components/src/components/btc-cascader/index.vue')['default']
    BtcConfigForm: typeof import('./components/btc-config-form/index.vue')['default']
    BtcConfigFormItem: typeof import('./components/btc-config-form/btc-config-form-item.vue')['default']
    BtcDialog: typeof import('@btc/shared-components')['BtcDialog']
    BtcForm: typeof import('@btc/shared-components')['BtcForm']
    BtcMasterList: typeof import('./../../../packages/shared-components/src/components/btc-master-list/index.vue')['default']
    BtcMessage: typeof import('./../../../packages/shared-components/src/components/btc-message/index.vue')['default']
    BtcNotification: typeof import('./../../../packages/shared-components/src/components/btc-notification/index.vue')['default']
    BtcSvg: typeof import('@btc/shared-components')['BtcSvg']
    BtcTableGroup: typeof import('./../../../packages/shared-components/src/components/btc-table-group/index.vue')['default']
    BtcTabs: typeof import('./../../../packages/shared-components/src/components/btc-tabs/index.vue')['default']
    BtcUpload: typeof import('./../../../packages/shared-components/src/components/btc-upload/index.vue')['default']
    BtcViewsTabsGroup: typeof import('./../../../packages/shared-components/src/components/btc-views-tabs-group/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMessage: typeof import('element-plus/es')['ElMessage']
    ElNotification: typeof import('element-plus/es')['ElNotification']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconBtn: typeof import('./components/IconBtn.vue')['default']
    RetryStatusIndicator: typeof import('./components/RetryStatusIndicator/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./components/TestComponent.vue')['default']
    UploadItem: typeof import('./../../../packages/shared-components/src/components/btc-upload/components/upload-item.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
