import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"修复 SVG 插件双连字符 Bug","description":"","frontmatter":{"title":"修复 SVG 插件双连字符 Bug","type":"adr","project":"technical","owner":"dev-team","created":"2025-10-11","updated":"2025-10-13","publish":true,"tags":["adr","technical","svg","plugin"],"sidebar_label":"SVG 插件修复","sidebar_order":1,"sidebar_group":"adr-technical"},"headers":[],"relativePath":"adr/technical/svg-plugin-fix.md","filePath":"adr/technical/svg-plugin-fix.md","lastUpdated":1760420026000}');
const _sfc_main = { name: "adr/technical/svg-plugin-fix.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="adr-修复-svg-插件双连字符-bug" tabindex="-1">ADR: 修复 SVG 插件双连字符 Bug <a class="header-anchor" href="#adr-修复-svg-插件双连字符-bug" aria-label="Permalink to &quot;ADR: 修复 SVG 插件双连字符 Bug&quot;">​</a></h1><blockquote><p><strong>状态</strong>: 已采纳<br><strong>日期</strong>: 2025-10-11<br><strong>决策者</strong>: 开发团队<br><strong>影响范围</strong>: SVG 图标系统和构建工具</p></blockquote><hr><h2 id="context" tabindex="-1">Context <a class="header-anchor" href="#context" aria-label="Permalink to &quot;Context&quot;">​</a></h2><p>SVG 插件在扫描 <code>src/assets/icons/</code> 目录时，生成的 symbol ID 出现双连字符（<code>icon--lang</code>），导致 btc-svg 组件查找失败（查找 <code>icon-lang</code>）</p><p>根因：</p><ul><li>插件在非模块目录扫描时，<code>moduleName</code> 为空字符串</li><li>拼接逻辑：<code>moduleName + &#39;-&#39; + baseName</code> <code>&#39;&#39; + &#39;-&#39; + &#39;lang&#39;</code> <code>&#39;-lang&#39;</code></li><li>最终生成 ID：<code>icon-</code> + <code>-lang</code> = <code>icon--lang</code></li></ul><h2 id="options" tabindex="-1">Options <a class="header-anchor" href="#options" aria-label="Permalink to &quot;Options&quot;">​</a></h2><ul><li><p><strong>Option A: 修改 btc-svg 组件查找逻辑</strong></p></li><li><p>优点: 不改插件</p></li><li><p>缺点: 违反直觉，ID 不应该有双连字符</p></li><li><p><strong>Option B: 修复插件拼接逻辑</strong></p></li><li><p>优点: 从根源解决，ID 命名规范</p></li><li><p>缺点: 需要重新构建插件</p></li><li><p><strong>Option C: 跳过空目录扫描</strong></p></li><li><p>优点: 简单</p></li><li><p>缺点: 无法使用 assets/icons 目录</p></li></ul><h2 id="decision" tabindex="-1">Decision <a class="header-anchor" href="#decision" aria-label="Permalink to &quot;Decision&quot;">​</a></h2><p>采用 <strong>Option B: 修复插件拼接逻辑</strong></p><p>在 <code>packages/vite-plugin/src/svg/index.ts</code> 添加判断：</p><div class="language-typescript vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 如果 moduleName 为空，跳过拼接</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">if</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">moduleName) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">shouldSkip </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> true</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>这样：</p><ul><li><code>moduleName</code> 为空 <code>shouldSkip = true</code> <code>iconName = baseName</code></li><li>生成 ID: <code>icon-</code> + <code>lang</code> = <code>icon-lang</code></li></ul><h2 id="consequences" tabindex="-1">Consequences <a class="header-anchor" href="#consequences" aria-label="Permalink to &quot;Consequences&quot;">​</a></h2><p><strong>正向影响</strong>:</p><ul><li>Symbol ID 命名规范，无双连字符</li><li>与 btc-svg 组件查找逻辑一致</li><li>扩展性好，未来新增图标目录也能正常工作</li></ul><p><strong>负向影响/需要注意</strong>:</p><ul><li>需要重新构建插件包：<code>pnpm --filter @btc/vite-plugin build</code></li><li>需要重启应用才能生效</li></ul><p><strong>行动项</strong>:</p><ul><li>[x] 修改插件代码</li><li>[x] 重新构建插件</li><li>[x] 验证图标显示正常</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("adr/technical/svg-plugin-fix.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const svgPluginFix = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  svgPluginFix as default
};
