import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"快速设置指南 - 局域网访问文档中心","description":"","frontmatter":{"title":"快速设置指南 - 局域网访问文档中心","type":"overview","project":"btc-shopflow","owner":"dev-team","created":"2025-10-14","updated":"2025-10-14","publish":true,"tags":["overview","setup","network"],"sidebar_label":"快速设置","sidebar_order":2,"sidebar_group":"overview"},"headers":[],"relativePath":"overview/quick-setup.md","filePath":"overview/quick-setup.md","lastUpdated":1760420026000}');
const _sfc_main = { name: "overview/quick-setup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="快速设置指南-局域网访问文档中心" tabindex="-1">快速设置指南 - 局域网访问文档中心 <a class="header-anchor" href="#快速设置指南-局域网访问文档中心" aria-label="Permalink to &quot;快速设置指南 - 局域网访问文档中心&quot;">​</a></h1><h2 id="问题" tabindex="-1">问题 <a class="header-anchor" href="#问题" aria-label="Permalink to &quot;问题&quot;">​</a></h2><p>默认情况下，文档中心运行在 <code>localhost:8085</code>，只有本机能访问其他PC无法访问</p><h2 id="解决方案" tabindex="-1">解决方案 <a class="header-anchor" href="#解决方案" aria-label="Permalink to &quot;解决方案&quot;">​</a></h2><p>使用环境变量配置，支持通过IP地址访问</p><h2 id="快速设置步骤" tabindex="-1">快速设置步骤 <a class="header-anchor" href="#快速设置步骤" aria-label="Permalink to &quot;快速设置步骤&quot;">​</a></h2><h3 id="_1-获取您的ip地址" tabindex="-1">1. 获取您的IP地址 <a class="header-anchor" href="#_1-获取您的ip地址" aria-label="Permalink to &quot;1. 获取您的IP地址&quot;">​</a></h3><p><strong>Windows:</strong></p><div class="language-powershell vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">powershell</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">ipconfig</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><p>查找&quot;IPv4 地址&quot;，例如：<code>10.80.8.199</code></p><p><strong>Mac/Linux:</strong></p><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">ifconfig</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> grep</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> inet</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="_2-配置文档中心地址" tabindex="-1">2. 配置文档中心地址 <a class="header-anchor" href="#_2-配置文档中心地址" aria-label="Permalink to &quot;2. 配置文档中心地址&quot;">​</a></h3><p><strong>方法 A：创建配置文件（推荐）</strong></p><p>在 <code>apps/main-app/</code> 目录下创建 <code>.env.development.local</code> 文件：</p><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 文档中心地址（局域网访问）</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">VITE_DOCS_URL</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">http://10.80.8.199:8085</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p><strong>方法 B：修改现有配置</strong></p><p>编辑 <code>apps/main-app/.env.development</code> 文件：</p><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 将 localhost 改为您的 IP 地址</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">VITE_DOCS_URL</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">http://10.80.8.199:8085</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="_3-重启应用" tabindex="-1">3. 重启应用 <a class="header-anchor" href="#_3-重启应用" aria-label="Permalink to &quot;3. 重启应用&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 停止当前运行的应用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">Ctrl</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> +</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> C</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 重新启动</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev:main</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="_4-验证访问" tabindex="-1">4. 验证访问 <a class="header-anchor" href="#_4-验证访问" aria-label="Permalink to &quot;4. 验证访问&quot;">​</a></h3><ol><li>本机访问：<a href="http://localhost:8080" target="_blank" rel="noreferrer">http://localhost:8080</a></li><li>其他PC访问：<a href="http://10.80.8.199:8080" target="_blank" rel="noreferrer">http://10.80.8.199:8080</a></li><li>点击&quot;文档中心&quot;菜单，应该能正常访问文档</li></ol><h2 id="防火墙配置" tabindex="-1">防火墙配置 <a class="header-anchor" href="#防火墙配置" aria-label="Permalink to &quot;防火墙配置&quot;">​</a></h2><p>如果其他PC仍无法访问，请检查防火墙设置：</p><h3 id="windows-防火墙" tabindex="-1">Windows 防火墙 <a class="header-anchor" href="#windows-防火墙" aria-label="Permalink to &quot;Windows 防火墙&quot;">​</a></h3><ol><li>打开&quot;Windows Defender 防火墙&quot;</li><li>点击&quot;允许应用或功能通过 Windows Defender 防火墙&quot;</li><li>找到&quot;Node.js JavaScript Runtime&quot;，确保&quot;专用&quot;和&quot;公用&quot;都勾选</li></ol><h3 id="临时关闭防火墙-测试用" tabindex="-1">临时关闭防火墙（测试用） <a class="header-anchor" href="#临时关闭防火墙-测试用" aria-label="Permalink to &quot;临时关闭防火墙（测试用）&quot;">​</a></h3><div class="language-powershell vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">powershell</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 管理员权限运行</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">netsh advfirewall set allprofiles state off</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>** 注意：测试完成后请重新开启防火墙**</p><h2 id="网络故障排除" tabindex="-1">网络故障排除 <a class="header-anchor" href="#网络故障排除" aria-label="Permalink to &quot;网络故障排除&quot;">​</a></h2><h3 id="检查端口占用" tabindex="-1">检查端口占用 <a class="header-anchor" href="#检查端口占用" aria-label="Permalink to &quot;检查端口占用&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 检查端口是否被占用</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">netstat</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -ano</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> findstr</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> :8085</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">netstat</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> -ano</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> findstr</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> :8080</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="检查网络连通性" tabindex="-1">检查网络连通性 <a class="header-anchor" href="#检查网络连通性" aria-label="Permalink to &quot;检查网络连通性&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 从其他PC ping 您的机器</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">ping</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 10.80.8.199</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 检查端口是否开放</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">telnet</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 10.80.8.199</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> 8085</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="常见问题" tabindex="-1">常见问题 <a class="header-anchor" href="#常见问题" aria-label="Permalink to &quot;常见问题&quot;">​</a></h3><ol><li><strong>端口被占用</strong></li></ol><ul><li>解决方案：更换端口或终止占用进程</li></ul><ol start="2"><li><strong>防火墙阻止</strong></li></ol><ul><li>解决方案：配置防火墙规则</li></ul><ol start="3"><li><strong>网络不通</strong></li></ol><ul><li>解决方案：检查IP地址和网络配置</li></ul><ol start="4"><li><strong>VitePress 配置问题</strong></li></ol><ul><li>解决方案：确保 <code>host: &#39;0.0.0.0&#39;</code> 配置正确</li></ul><h2 id="生产环境配置" tabindex="-1">生产环境配置 <a class="header-anchor" href="#生产环境配置" aria-label="Permalink to &quot;生产环境配置&quot;">​</a></h2><p>生产环境不需要特殊配置，因为：</p><ul><li>使用反向代理（如 Nginx）</li><li>通过域名访问</li><li>防火墙规则已配置</li></ul><h2 id="相关文档" tabindex="-1">相关文档 <a class="header-anchor" href="#相关文档" aria-label="Permalink to &quot;相关文档&quot;">​</a></h2><ul><li><a href="/internal/archive/guides/deployment">部署指南</a></li><li><a href="/internal/archive/guides/network">网络配置</a></li><li><a href="/internal/archive/guides/troubleshooting">故障排除</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("overview/quick-setup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const quickSetup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  quickSetup as default
};
