import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"🏷 类型索引","description":"","frontmatter":{"title":"🏷 类型索引","type":"guide","project":"btc-shopflow","owner":"dev-team","created":"2025-10-13","updated":"2025-10-13","publish":true,"tags":[],"sidebar_label":"🏷 类型索引","sidebar_order":0,"sidebar_collapsed":false},"headers":[],"relativePath":"types/index.md","filePath":"types/index.md","lastUpdated":1760420026000}');
const _sfc_main = { name: "types/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="类型索引" tabindex="-1">类型索引 <a class="header-anchor" href="#类型索引" aria-label="Permalink to &quot;类型索引&quot;">​</a></h1><blockquote><p>按文档类型分类</p></blockquote><div class="tip custom-block"><p class="custom-block-title">提示</p><p>目前还没有收录任何文档请运行 <code>pnpm --filter docs-site ingest</code> 来收录文档</p></div><h2 id="文档类型说明" tabindex="-1">文档类型说明 <a class="header-anchor" href="#文档类型说明" aria-label="Permalink to &quot;文档类型说明&quot;">​</a></h2><h3 id="guide-功能指南" tabindex="-1">guide - 功能指南 <a class="header-anchor" href="#guide-功能指南" aria-label="Permalink to &quot;guide - 功能指南&quot;">​</a></h3><p>功能使用指南最佳实践使用教程</p><h3 id="api-api-文档" tabindex="-1">api - API 文档 <a class="header-anchor" href="#api-api-文档" aria-label="Permalink to &quot;api - API 文档&quot;">​</a></h3><p>组件 API函数 API类型定义</p><h3 id="decision-架构决策-adr" tabindex="-1">decision - 架构决策 (ADR) <a class="header-anchor" href="#decision-架构决策-adr" aria-label="Permalink to &quot;decision - 架构决策 (ADR)&quot;">​</a></h3><p>重要的技术决策架构选型设计权衡</p><h3 id="howto-操作手册-sop" tabindex="-1">howto - 操作手册 (SOP) <a class="header-anchor" href="#howto-操作手册-sop" aria-label="Permalink to &quot;howto - 操作手册 (SOP)&quot;">​</a></h3><p>标准操作流程部署步骤故障排查</p><h3 id="summary-总结归纳" tabindex="-1">summary - 总结归纳 <a class="header-anchor" href="#summary-总结归纳" aria-label="Permalink to &quot;summary - 总结归纳&quot;">​</a></h3><p>项目总结迁移报告完成总结</p><h3 id="rca-问题根因分析" tabindex="-1">rca - 问题根因分析 <a class="header-anchor" href="#rca-问题根因分析" aria-label="Permalink to &quot;rca - 问题根因分析&quot;">​</a></h3><p>问题分析故障复盘根因追溯</p><h3 id="retro-复盘回顾" tabindex="-1">retro - 复盘回顾 <a class="header-anchor" href="#retro-复盘回顾" aria-label="Permalink to &quot;retro - 复盘回顾&quot;">​</a></h3><p>项目复盘经验总结改进建议</p><h3 id="checklist-检查清单" tabindex="-1">checklist - 检查清单 <a class="header-anchor" href="#checklist-检查清单" aria-label="Permalink to &quot;checklist - 检查清单&quot;">​</a></h3><p>发布检查质量检查安全检查</p><h2 id="如何收录文档" tabindex="-1">如何收录文档 <a class="header-anchor" href="#如何收录文档" aria-label="Permalink to &quot;如何收录文档&quot;">​</a></h2><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 1. 为文档添加 frontmatter（指定 type）</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --filter</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> docs-site</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> add-frontmatter</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># 2. 运行收录脚本</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> --filter</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> docs-site</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ingest</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><p>收录完成后，此页面会按类型自动生成索引</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("types/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
