/**
 * 访问控制模块配置
 * 包含国际化配置、表格列配置和表单配置
 */

import type { PageConfig } from '../../../../../types/locale';
import type { TableColumn, FormItem } from '@btc/shared-components';
import { service } from '@services/eps';

export default {
  // 国际化配置（扁平结构）
  locale: {
    'zh-CN': {
      // 菜单配置
      'menu.access': '权限管理',
      'menu.access.config': '基础配置',
      'menu.access.resources': '资源列表',
      'menu.access.actions': '行为列表',
      'menu.access.permissions': '权限列表',
      'menu.access.roles': '角色列表',
      'menu.access.role_perm_bind': '角色权限绑定',
      'menu.access.relations': '资源分配',
      'menu.access.perm_compose': '权限组合',
      'menu.access.user_assign': '用户分配',
      'menu.access.user_role_bind': '角色绑定',
      'menu.access.role_assign': '角色分配',
      'menu.access.role_permission_bind': '权限绑定',
      // 字段配置
      'access.actions.fields.action_name_cn': '行为名称',
      'access.actions.fields.action_code': '行为编码',
      'access.actions.fields.action_type': '类型',
      'access.actions.fields.http_method': 'HTTP方法',
      'access.actions.fields.description': '描述',
      'access.permissions.fields.perm_name': '权限名称',
      'access.permissions.fields.perm_code': '权限编码',
      'access.permissions.fields.perm_type': '权限类型',
      'access.permissions.fields.perm_category': '权限分类',
      'access.permissions.fields.module_id': '模块ID',
      'access.permissions.fields.plugin_id': '插件ID',
      'access.permissions.fields.description': '描述',
      'access.resources.sync': '数据同步',
      'access.resources.sync_success': '数据同步成功',
      'access.resources.sync_failed': '数据同步失败',
      'access.resources.fields.resource_name_cn': '资源名称',
      'access.resources.fields.resource_code': '资源编码',
      'access.resources.fields.resource_type': '类型',
      'access.resources.fields.description': '描述',
      'access.resources.types.file': '文件',
      'access.resources.types.api': 'API',
      'access.resources.types.table': '数据表',
      'access.roles.fields.role_name': '角色名称',
      'access.roles.fields.role_code': '角色编码',
      'access.roles.fields.role_type': '角色类型',
      'access.roles.fields.parent_id': '父级角色',
      'access.roles.fields.domain_id': '所属域',
      'access.roles.fields.description': '描述',
      'access.roles.types.admin': '管理员',
      'access.roles.types.business': '业务员',
      'access.roles.types.guest': '访客',
      // 操作提示
      'access.action_name': '行为名称',
      'access.action_code': '行为编码',
      'access.type': '类型',
      'access.http_method': 'HTTP方法',
      'access.description': '描述',
      'access.permission_name': '权限名称',
      'access.permission_code': '权限编码',
      'access.permission_type': '权限类型',
      'access.permission_category': '权限分类',
      'access.module_id': '模块ID',
      'access.plugin_id': '插件ID',
      'access.data_sync': '数据同步',
      'access.data_sync_success': '数据同步成功',
      'access.data_sync_failed': '数据同步失败',
      'access.resource_name': '资源名称',
      'access.resource_code': '资源编码',
      'access.role_name': '角色名称',
      'access.role_code': '角色编码',
      'access.role_type': '角色类型',
      'access.parent_role': '父级角色',
      'access.domain': '所属域',
      'access.file': '文件',
      'access.data_table': '数据表',
      'access.admin': '管理员',
      'access.staff': '业务员',
      'access.guest': '访客',
      'access.none': '无',
      'access.unassigned': '未分配',
      'access.enter_role_name': '请输入角色名称',
      'access.enter_role_code': '请输入角色编码',
      'access.select_role_type': '请选择角色类型',
      'access.select_parent_role': '请选择父级角色',
      'access.select_domain': '请选择所属域',
      'access.enter_role_description': '请输入角色描述',
      'access.no_common_actions': '当前选中的资源没有任何共同支持的操作',
      'access.select_resource_and_action': '请至少选择一个资源和操作',
      'access.permission_of': '的权限',
      'access.no_permissions_to_add': '没有可添加的权限',
      'access.added': '已添加',
      'access.removed': '已移除',
      'access.matrix_mode': '矩阵模式',
      'access.compose_mode': '组合模式',
      'access.switched_to': '已切换到',
      'access.matrix': '矩阵',
      'access.compose': '组合',
      'access.mode': '模式',
      'access.deselected_all': '已取消全选',
      'access.selected_all': '已选择全部',
      'access.selected_readonly': '已选择只读权限',
      'access.selected_edit': '已选择编辑权限',
      'access.selected_full_crud': '已选择完整CRUD',
      'access.cleared_all': '已清空全部',
      'access.saved': '已保存',
      'access.clear_all': '清空全部',
      'access.save_permissions': '保存权限',
      'access.permission_matrix': '权限矩阵',
      'access.action_list': '操作列表',
      'access.select_all': '全选',
      'access.quick_select': '快速选择',
      'access.readonly_permission': '只读权限',
      'access.edit_permission': '编辑权限',
      'access.full_crud': '完整CRUD',
      'access.selected_permissions': '已选权限',
      'access.permission_preview': '权限预览',
      'access.count_unit': '个',
      'access.generate_permissions': '生成权限',
      'access.save_failed': '保存失败',
      'access.removed_permission': '已移除',
    },
    'en-US': {
      // 菜单配置
      'menu.access': 'Access Control',
      'menu.access.config': 'Configuration',
      'menu.access.resources': 'Resource List',
      'menu.access.actions': 'Action List',
      'menu.access.permissions': 'Permission List',
      'menu.access.roles': 'Role List',
      'menu.access.role_perm_bind': 'Role Permission Binding',
      'menu.access.relations': 'Resource Assignment',
      'menu.access.perm_compose': 'Permission Composition',
      'menu.access.user_assign': 'User Assignment',
      'menu.access.user_role_bind': 'Role Binding',
      'menu.access.role_assign': 'Role Assignment',
      'menu.access.role_permission_bind': 'Permission Binding',
      // 字段配置
      'access.actions.fields.action_name_cn': 'Action Name',
      'access.actions.fields.action_code': 'Action Code',
      'access.actions.fields.action_type': 'Type',
      'access.actions.fields.http_method': 'HTTP Method',
      'access.actions.fields.description': 'Description',
      'access.permissions.fields.perm_name': 'Permission Name',
      'access.permissions.fields.perm_code': 'Permission Code',
      'access.permissions.fields.perm_type': 'Permission Type',
      'access.permissions.fields.perm_category': 'Permission Category',
      'access.permissions.fields.module_id': 'Module ID',
      'access.permissions.fields.plugin_id': 'Plugin ID',
      'access.permissions.fields.description': 'Description',
      'access.resources.sync': 'Data Sync',
      'access.resources.sync_success': 'Data sync successful',
      'access.resources.sync_failed': 'Data sync failed',
      'access.resources.fields.resource_name_cn': 'Resource Name',
      'access.resources.fields.resource_code': 'Resource Code',
      'access.resources.fields.resource_type': 'Type',
      'access.resources.fields.description': 'Description',
      'access.resources.types.file': 'File',
      'access.resources.types.api': 'API',
      'access.resources.types.table': 'Data Table',
      'access.roles.fields.role_name': 'Role Name',
      'access.roles.fields.role_code': 'Role Code',
      'access.roles.fields.role_type': 'Role Type',
      'access.roles.fields.parent_id': 'Parent Role',
      'access.roles.fields.domain_id': 'Domain',
      'access.roles.fields.description': 'Description',
      'access.roles.types.admin': 'Administrator',
      'access.roles.types.business': 'Staff',
      'access.roles.types.guest': 'Guest',
      // 操作提示
      'access.action_name': 'Action Name',
      'access.action_code': 'Action Code',
      'access.type': 'Type',
      'access.http_method': 'HTTP Method',
      'access.description': 'Description',
      'access.permission_name': 'Permission Name',
      'access.permission_code': 'Permission Code',
      'access.permission_type': 'Permission Type',
      'access.permission_category': 'Permission Category',
      'access.module_id': 'Module ID',
      'access.plugin_id': 'Plugin ID',
      'access.data_sync': 'Data Sync',
      'access.data_sync_success': 'Data sync successful',
      'access.data_sync_failed': 'Data sync failed',
      'access.resource_name': 'Resource Name',
      'access.resource_code': 'Resource Code',
      'access.role_name': 'Role Name',
      'access.role_code': 'Role Code',
      'access.role_type': 'Role Type',
      'access.parent_role': 'Parent Role',
      'access.domain': 'Domain',
      'access.file': 'File',
      'access.data_table': 'Data Table',
      'access.admin': 'Administrator',
      'access.staff': 'Staff',
      'access.guest': 'Guest',
      'access.none': 'None',
      'access.unassigned': 'Unassigned',
      'access.enter_role_name': 'Please enter role name',
      'access.enter_role_code': 'Please enter role code',
      'access.select_role_type': 'Please select role type',
      'access.select_parent_role': 'Please select parent role',
      'access.select_domain': 'Please select domain',
      'access.enter_role_description': 'Please enter role description',
      'access.no_common_actions': 'Currently selected resources have no common supported actions',
      'access.select_resource_and_action': 'Please select at least one resource and action',
      'access.permission_of': 'permission of',
      'access.no_permissions_to_add': 'No permissions to add',
      'access.added': 'Added',
      'access.removed': 'Removed',
      'access.matrix_mode': 'Matrix Mode',
      'access.compose_mode': 'Compose Mode',
      'access.switched_to': 'Switched to',
      'access.matrix': 'Matrix',
      'access.compose': 'Compose',
      'access.mode': 'Mode',
      'access.deselected_all': 'Deselected all',
      'access.selected_all': 'Selected all',
      'access.selected_readonly': 'Selected readonly permissions',
      'access.selected_edit': 'Selected edit permissions',
      'access.selected_full_crud': 'Selected full CRUD',
      'access.cleared_all': 'Cleared all',
      'access.saved': 'Saved',
      'access.clear_all': 'Clear All',
      'access.save_permissions': 'Save Permissions',
      'access.permission_matrix': 'Permission Matrix',
      'access.action_list': 'Action List',
      'access.select_all': 'Select All',
      'access.quick_select': 'Quick Select',
      'access.readonly_permission': 'Readonly Permission',
      'access.edit_permission': 'Edit Permission',
      'access.full_crud': 'Full CRUD',
      'access.selected_permissions': 'Selected Permissions',
      'access.permission_preview': 'Permission Preview',
      'access.count_unit': '',
      'access.generate_permissions': 'Generate Permissions',
      'access.save_failed': 'Save Failed',
    },
  },

  // 表格列配置
  columns: {
    'access.actions': [
      { type: 'selection', width: 60 },
      { type: 'index', label: 'common.index', width: 60 },
      { prop: 'actionNameCn', label: 'access.actions.fields.action_name_cn' },
      { prop: 'actionCode', label: 'access.actions.fields.action_code' },
      { prop: 'actionType', label: 'access.actions.fields.action_type' },
      { prop: 'httpMethod', label: 'access.actions.fields.http_method' },
      { prop: 'description', label: 'common.description' },
    ] as TableColumn[],

    'access.permissions': [
      { type: 'selection', width: 60 },
      { type: 'index', label: 'common.index', width: 60 },
      { prop: 'permName', label: 'access.permissions.fields.perm_name', minWidth: 150, showOverflowTooltip: true },
      { prop: 'permCode', label: 'access.permissions.fields.perm_code', minWidth: 150, showOverflowTooltip: true },
      { prop: 'permType', label: 'access.permissions.fields.perm_type', minWidth: 100 },
      { prop: 'permCategory', label: 'access.permissions.fields.perm_category', minWidth: 100 },
      { prop: 'moduleId', label: 'platform.module.name', minWidth: 120 },
      { prop: 'pluginId', label: 'platform.plugin.name', minWidth: 120 },
      { prop: 'description', label: 'common.description', minWidth: 150, showOverflowTooltip: true },
      { prop: 'createdAt', label: 'common.create_time', minWidth: 160, formatter: (row: any) => row.createdAt ? new Date(row.createdAt).toLocaleString() : '-' },
    ] as TableColumn[],

    'access.resources': [
      { type: 'index', label: 'common.index', width: 60 },
      { prop: 'resourceNameCn', label: 'access.resources.fields.resource_name_cn', minWidth: 150 },
      { prop: 'resourceCode', label: 'access.resources.fields.resource_code', minWidth: 150 },
      {
        prop: 'resourceType',
        label: 'access.resources.fields.resource_type',
        width: 120,
        dict: [
          { label: 'access.resources.types.file', value: 'FILE', type: 'info' },
          { label: 'access.resources.types.api', value: 'API', type: 'warning' },
          { label: 'access.resources.types.table', value: 'TABLE', type: 'primary' },
        ],
        dictColor: true,
      },
      { prop: 'description', label: 'common.description', minWidth: 200 },
    ] as TableColumn[],

    'access.roles': [
      { type: 'selection', width: 60 },
      { type: 'index', label: 'common.index', width: 60 },
      { prop: 'roleName', label: 'access.roles.fields.role_name', minWidth: 150 },
      { prop: 'roleCode', label: 'access.roles.fields.role_code', width: 180 },
      {
        prop: 'roleType',
        label: 'access.roles.fields.role_type',
        width: 100,
        dict: [
          { label: 'access.roles.types.admin', value: 'ADMIN', type: 'danger' },
          { label: 'access.roles.types.business', value: 'BUSINESS', type: 'success' },
          { label: 'access.roles.types.guest', value: 'GUEST', type: 'info' },
        ],
        dictColor: true,
      },
      {
        prop: 'parentId',
        label: 'access.roles.fields.parent_id',
        width: 100,
        formatter: (row: any) => {
          // formatter 需要在页面中动态处理
          return row.parentId === '0' ? 'access.none' : row.parentId;
        },
      },
      {
        prop: 'domainId',
        label: 'access.roles.fields.domain_id',
        width: 100,
        formatter: (row: any) => {
          // formatter 需要在页面中动态处理
          return row.domainId || 'access.unassigned';
        },
      },
      { prop: 'description', label: 'common.description', minWidth: 200, showOverflowTooltip: true },
      { prop: 'createdAt', label: 'common.create_time', width: 160, sortable: true },
    ] as TableColumn[],
  },

  // 表单配置
  forms: {
    'access.actions': [
      { prop: 'actionNameCn', label: 'access.actions.fields.action_name_cn', span: 12, required: true, component: { name: 'el-input' } },
      { prop: 'actionCode', label: 'access.actions.fields.action_code', span: 12, required: true, component: { name: 'el-input' } },
      { prop: 'actionType', label: 'access.actions.fields.action_type', span: 12, component: { name: 'el-input' } },
      { prop: 'httpMethod', label: 'access.actions.fields.http_method', span: 12, component: { name: 'el-input' } },
      { prop: 'description', label: 'common.description', span: 24, component: { name: 'el-input', props: { type: 'textarea' } } },
    ] as FormItem[],

    'access.permissions': [
      { prop: 'permName', label: 'access.permissions.fields.perm_name', span: 12, required: true, component: { name: 'el-input' } },
      { prop: 'permCode', label: 'access.permissions.fields.perm_code', span: 12, required: true, component: { name: 'el-input' } },
      { prop: 'permType', label: 'access.permissions.fields.perm_type', span: 12, component: { name: 'el-input' } },
      { prop: 'permCategory', label: 'access.permissions.fields.perm_category', span: 12, component: { name: 'el-input' } },
      { prop: 'moduleId', label: 'platform.module.name', span: 12, component: { name: 'el-input' } },
      { prop: 'pluginId', label: 'platform.plugin.name', span: 12, component: { name: 'el-input' } },
      { prop: 'description', label: 'common.description', span: 24, component: { name: 'el-input', props: { type: 'textarea', rows: 3 } } },
    ] as FormItem[],

    'access.resources': [
      { prop: 'resourceNameCn', label: 'access.resources.fields.resource_name_cn', span: 12, required: true, component: { name: 'el-input' } },
      { prop: 'resourceCode', label: 'access.resources.fields.resource_code', span: 12, required: true, component: { name: 'el-input' } },
      {
        prop: 'resourceType',
        label: 'access.resources.fields.resource_type',
        span: 12,
        component: {
          name: 'el-select',
          options: [
            { label: 'access.resources.types.file', value: 'FILE' },
            { label: 'access.resources.types.api', value: 'API' },
            { label: 'access.resources.types.table', value: 'TABLE' },
          ],
        },
      },
      { prop: 'description', label: 'common.description', span: 24, component: { name: 'el-input', props: { type: 'textarea', rows: 3 } } },
    ] as FormItem[],

    'access.roles': [
      {
        prop: 'roleName',
        label: 'access.roles.fields.role_name',
        span: 12,
        required: true,
        component: {
          name: 'el-input',
          props: {
            placeholder: 'access.enter_role_name',
          },
        },
      },
      {
        prop: 'roleCode',
        label: 'access.roles.fields.role_code',
        span: 12,
        required: true,
        component: {
          name: 'el-input',
          props: {
            placeholder: 'access.enter_role_code',
          },
        },
      },
      {
        prop: 'roleType',
        label: 'access.roles.fields.role_type',
        span: 12,
        required: true,
        component: {
          name: 'el-select',
          props: {
            placeholder: 'access.select_role_type',
            clearable: true,
          },
          options: [
            { label: 'access.roles.types.admin', value: 'ADMIN' },
            { label: 'access.roles.types.business', value: 'BUSINESS' },
            { label: 'access.roles.types.guest', value: 'GUEST' },
          ],
        },
      },
      {
        prop: 'parentId',
        label: 'access.roles.fields.parent_id',
        span: 12,
        component: {
          name: 'btc-cascader',
          props: {
            placeholder: 'access.select_parent_role',
            clearable: true,
            filterable: true,
            // options 需要在页面中动态传入
          },
        },
      },
      {
        prop: 'domainId',
        label: 'access.roles.fields.domain_id',
        span: 12,
        component: {
          name: 'btc-cascader',
          props: {
            placeholder: 'access.select_domain',
            clearable: true,
            filterable: true,
            // options 需要在页面中动态传入
          },
        },
      },
      {
        prop: 'description',
        label: 'common.description',
        span: 24,
        component: {
          name: 'el-input',
          props: {
            type: 'textarea',
            rows: 3,
            placeholder: 'access.enter_role_description',
          },
        },
      },
    ] as FormItem[],
  },

  // 服务配置
  service: {
    action: service.admin?.iam?.action,
    permission: service.admin?.iam?.permission,
    resource: service.admin?.iam?.resource,
    role: service.admin?.iam?.role,
    domain: service.admin?.iam?.domain,
    // BtcTableGroup 需要的左右服务
    sysdomain: service.admin?.iam?.domain,
    sysrole: service.admin?.iam?.role,
  },
} satisfies PageConfig;
